# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedjack', '0015_auto_20150209_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedjack.Group', verbose_name='parent group')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='author email'),
        ),
        migrations.AlterField(
            model_name='site',
            name='links',
            field=models.ManyToManyField(blank=True, to='feedjack.Link', verbose_name='links'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedjack.Group', verbose_name='group'),
        ),
    ]
