# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedjack', '0016_add_group_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[(b'U', b'Unread'), (b'R', b'Read'), (b'T', b'To Read'), (b'I', b'Important'), (b'F', b'Favourite')], max_length=1, db_index=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedjack.Post', db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='marked',
            field=models.ManyToManyField(blank=True, through='feedjack.PostMark', to=settings.AUTH_USER_MODEL),
        ),
    ]
