# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('feedjack', '0017_post_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='django_site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
    ]
