# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedjack', '0018_use_django_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmark',
            name='mark',
            field=models.CharField(choices=[(b'U', b'Unread'), (b'R', b'Read'), (b'T', b'To Read'), (b'I', b'Important'), (b'F', b'Favorite')], db_index=True, max_length=1),
        ),
    ]
